Fix npm test
No idea what was going on, but “npm audit fix --force” downgraded mocha
and this fixed the “npm test” issue:

$ npm test

> test
> mocha tests/*.js

file:///home/runner/work/build-shaper-font/build-shaper-font/node_modules/yargs/yargs:3
const {applyExtends, cjsPlatformShim, Parser, Yargs, processArgv} = require('./build/index.cjs')
                                                                    ^

ReferenceError: require is not defined in ES module scope, you can use import instead
    at file:///home/runner/work/build-shaper-font/build-shaper-font/node_modules/yargs/yargs:3:69
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:534:37)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:366:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1648:24)
    at Module._compile (node:internal/modules/cjs/loader:1813:5)
    at Object..js (node:internal/modules/cjs/loader:1971:10)
    at Module.load (node:internal/modules/cjs/loader:1552:32)
    at Module._load (node:internal/modules/cjs/loader:1354:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.require (node:internal/modules/cjs/loader:1575:12)

Node.js v25.8.0